
// https://en.wikipedia.org/wiki/Arithmetic_function

bool is_odd(int n)
{
  return n % 2 == 1;
}

int abs(int n)
{
  return n < 0 ? -n : n;
}

int max(int a, int b)
{
  return a > b ? a : b;
}

int min(int a, int b)
{
  return a > b ? b : a;
}

int factorial(int n)
{
  if(n <= 1)
    return 1;
  return n * factorial(n-1);
}

int pow(int x, int n)
{
  int y = 1;

  while(n != 0)
  {
    if(n % 2 == 1)
      y = y * x;
    else
      x = x * x;
    n >>= 1;
  }

  return y;
}

int modpow(int x, int n, int m)
{
  if(n == 0)
    return 1;

  if(n % 2 == 1)
    return (x * modpow((x*x) % m, n / 2, m)) % m;
  else
    return modpow((x*x) % m, n / 2, m) % m;
}

int gcd(int a, int b)
{
  if(b == 0)
    return a;
  else
    return gcd(b, a % b);
}

int lcm(int a, int b)
{
  return (a * b) / gcd(a, b);
}

bool coprime(int a, int b)
{
  return gcd(a, b) == 1;
}

int phi(int n)
{
  int p = 0;

  for(int i(1); i <= n; ++i)
  {
    if(coprime(i, n))
      ++p;
  }

  return p;
}

int sigma(int n)
{
  int s = 0;

  for(int i(1); i <= n; ++i)
  {
    if(n % i == 0)
      s += i;
  }

  return s;
}

bool is_perfect(int n)
{
  return sigma(n) == 2*n;
}

bool is_prime(int n)
{
  if(is_odd(n))
    return false;

  for(int i(3); i*i <= n; i +=2)
  {
    if(n % i == 0)
      return false;
  }

  return true;
}

int pi(int x)
{
  int r = 0;

  for(int n(2); n <= x; ++n)
  {
    if(is_prime(n))
      ++r;    
  }

  return r;
}

int nCr(int n, int r)
{
  if(r == 0 || r == n)
    return 1;
  else if(r == 1 || r == n - 1)
    return n;

  return nCr(n-1, r-1) + nCr(n-1, r);
}

int fib(int n)
{
  if(n == 0)
    return 0;
  if(n == 1)
    return 1;

  return fib(n-1) + fib(n-2);
}

int syracuse(int n)
{
  int iter = 0;

  while(n != 1)
  {
    if(is_odd(n))
      n = 3*n + 1;
    else
      n = n / 2;

    ++iter;
  }

  return iter;
}

int Mp(int p)
{
  return pow(2, p) - 1;
}


Assert(is_odd(3));
Assert(abs(-2) == 2);
Assert(max(1, 2) == 2);
Assert(factorial(6) == 720);
Assert(pow(2, 16) == 65536);
Assert(gcd(6, 8) == 2);
Assert(coprime(9, 10));
