// Copyright (C) 2018 Vincent Chambrin
// This file is part of the libscript library
// For conditions of distribution and use, see copyright notice in LICENSE

#ifndef LIBSCRIPT_ERROR_CODES_H
#define LIBSCRIPT_ERROR_CODES_H

namespace script
{

enum class ErrorCode {
  NoError = 0,
  NotImplementedError,
  RuntimeError,
  /* Engine errors */
  E_NoMatchingConstructor,
  E_ConstructorIsDeleted,
  E_TooManyArgumentInInitialization,
  E_TooFewArgumentInInitialization,
  E_CopyError,
  E_ConversionError,
  NoSuchArrayType,
  E_UnknownTypeError,
  E_EvaluationError,
  /* Parser errors */
  FirstParserError,
  P_UnexpectedEndOfInput = FirstParserError,
  P_UnexpectedFragmentEnd,
  P_UnexpectedToken,
  P_ExpectedEmptyStringLiteral,
  P_InvalidEmptyBrackets,
  P_IllegalUseOfKeyword,
  P_ExpectedIdentifier,
  P_ExpectedUserDefinedName,
  P_ExpectedLiteral,
  P_ExpectedOperator,
  P_ExpectedBinaryOperator,
  P_ExpectedPrefixOperator,
  P_ExpectedOperatorSymbol,
  P_InvalidEmptyOperand,
  P_ExpectedDeclaration,
  P_MissingConditionalColon,
  P_CouldNotParseLambdaCapture,
  P_ExpectedCurrentClassName,
  P_CouldNotReadType,
  LastParserError = P_CouldNotReadType,
  /* Compiler errors */
  FirstCompilerError,
  C_SyntaxError = FirstCompilerError,
  C_IllegalUseOfThis,
  C_ObjectHasNoDestructor,
  C_InvalidUseOfDelegatedConstructor,
  C_NotDataMember,
  C_InheritedDataMember,
  C_DataMemberAlreadyHasInitializer,
  C_NoDelegatingConstructorFound,
  C_CouldNotFindValidBaseConstructor,
  C_InitializerListAsFirstArrayElement,
  C_ReturnStatementWithoutValue,
  C_ReturnStatementWithValue,
  C_ReferencesMustBeInitialized,
  C_EnumerationsCannotBeDefaultConstructed,
  C_EnumerationsMustBeInitialized,
  C_FunctionVariablesMustBeInitialized,
  C_VariableCannotBeDefaultConstructed,
  C_ClassHasDeletedDefaultCtor,
  C_CouldNotResolveOperatorName,
  C_InvalidParamCountInOperatorOverload,
  C_OpOverloadMustBeDeclaredAsMember,
  C_InvalidTypeName,
  C_DataMemberCannotBeAuto,
  C_MissingStaticInitialization,
  C_InvalidStaticInitialization,
  C_FailedToInitializeStaticVariable,
  C_InvalidBaseClass,
  C_InvalidUseOfDefaultArgument,
  C_ArrayElementNotConvertible,
  C_ArraySubscriptOnNonObject,
  C_CouldNotFindValidSubscriptOperator,
  C_CannotCaptureThis,
  C_UnknownCaptureName,
  C_CannotCaptureNonCopyable,
  C_SomeLocalsCannotBeCaptured,
  C_CannotCaptureByValueAndByRef,
  C_LambdaMustBeCaptureless,
  C_CouldNotFindValidConstructor,
  C_CouldNotFindValidMemberFunction,
  C_CouldNotFindValidOperator,
  C_CouldNotFindValidCallOperator,
  C_AmbiguousFunctionName,
  C_TemplateNamesAreNotExpressions,
  C_TypeNameInExpression,
  C_NamespaceNameInExpression,
  C_TooManyArgumentInVariableInitialization,
  C_TooManyArgumentInInitialization,
  C_TooManyArgumentInReferenceInitialization,
  C_CouldNotConvert,
  C_CouldNotFindCommonType,
  C_CannotAccessMemberOfNonObject,
  C_NoSuchMember,
  C_InvalidTemplateArgument,
  C_InvalidLiteralTemplateArgument,
  C_MissingNonDefaultedTemplateParameter,
  C_CouldNotFindPrimaryClassTemplate,
  C_CouldNotFindPrimaryFunctionTemplate,
  C_InvalidUseOfConstKeyword,
  C_InvalidUseOfExplicitKeyword,
  C_InvalidUseOfStaticKeyword,
  C_InvalidUseOfVirtualKeyword,
  C_AutoMustBeUsedWithAssignment,
  C_CannotDeduceLambdaReturnType,
  C_CallToDeletedFunction,
  C_FunctionCannotBeDefaulted,
  C_ParentHasNoDefaultConstructor,
  C_ParentHasDeletedDefaultConstructor,
  C_ParentHasNoCopyConstructor,
  C_ParentHasDeletedCopyConstructor,
  C_DataMemberIsNotCopyable,
  C_ParentHasDeletedMoveConstructor,
  C_DataMemberIsNotMovable,
  C_ParentHasNoAssignmentOperator,
  C_ParentHasDeletedAssignmentOperator,
  C_DataMemberHasNoAssignmentOperator,
  C_DataMemberHasDeletedAssignmentOperator,
  C_DataMemberIsReferenceAndCannotBeAssigned,
  C_InvalidCharacterLiteral,
  C_CouldNotFindValidLiteralOperator,
  C_UnknownTypeInBraceInitialization,
  C_NarrowingConversionInBraceInitialization,
  C_NamespaceDeclarationCannotAppearAtThisLevel,
  C_ExpectedDeclaration,
  C_GlobalVariablesCannotBeAuto,
  C_GlobalVariablesMustBeInitialized,
  C_GlobalVariablesMustBeAssigned,
  C_InaccessibleMember,
  C_FriendMustBeAClass,
  C_UnknownModuleName,
  C_UnknownSubModuleName,
  C_ModuleImportationFailed,
  C_InvalidNameInUsingDirective,
  C_NoSuchCallee,
  C_LiteralOperatorNotInNamespace,
  LastCompilerError = C_LiteralOperatorNotInNamespace,
};

} // namespace script

#endif // LIBSCRIPT_EXCEPTION_H
